functional:
  -  adaptive_avg_pool1d
  -  adaptive_avg_pool2d
  -  adaptive_avg_pool3d
  -  adaptive_max_pool1d
  -  adaptive_max_pool2d
  -  adaptive_max_pool3d
  -  affine_grid
  -  alpha_dropout
  -  avg_pool1d
  -  avg_pool2d
  -  avg_pool3d
  -  batch_norm
  -  bilinear
  -  binary_cross_entropy
  -  binary_cross_entropy_with_logits
  -  celu
  -  channel_shuffle
  -  class_center_sample
  -  common
  -  conv
  -  conv1d
  -  conv1d_transpose
  -  conv2d
  -  conv2d_transpose
  -  conv3d
  -  conv3d_transpose
  -  cosine_embedding_loss
  -  cosine_similarity
  -  cross_entropy
  -  ctc_loss
  -  diag_embed
  -  dice_loss
  -  distance
  -  dropout
  -  dropout2d
  -  dropout3d
  -  elu
  -  elu_
  -  embedding
  -  extension
  -  flash_attention
  -  flash_attention_with_sparse_mask
  -  fractional_max_pool2d
  -  fractional_max_pool3d
  -  fold
  -  gather_tree
  -  gaussian_nll_loss
  -  gelu
  -  glu
  -  grid_sample
  -  gumbel_softmax
  -  hardshrink
  -  hardsigmoid
  -  hardswish
  -  hardtanh
  -  hardtanh_
  -  hinge_embedding_loss
  -  hsigmoid_loss
  -  instance_norm
  -  interpolate
  -  kl_div
  -  l1_loss
  -  label_smooth
  -  layer_norm
  -  leaky_relu
  -  leaky_relu_
  -  linear
  -  local_response_norm
  -  log_loss
  -  log_sigmoid
  -  log_softmax
  -  margin_cross_entropy
  -  margin_ranking_loss
  -  max_pool1d
  -  max_pool2d
  -  max_pool3d
  -  max_unpool1d
  -  max_unpool2d
  -  max_unpool3d
  -  maxout
  -  mish
  -  mse_loss
  -  multi_label_soft_margin_loss
  -  multi_margin_loss
  -  nll_loss
  -  norm
  -  normalize
  -  npair_loss
  -  one_hot
  -  pad
  -  pairwise_distance
  -  pdist
  -  pixel_shuffle
  -  pixel_unshuffle
  -  poisson_nll_loss
  -  pooling
  -  prelu
  -  relu
  -  relu6
  -  relu_
  -  rnnt_loss
  -  rrelu
  -  scaled_dot_product_attention
  -  sdp_kernel
  -  selu
  -  sequence_mask
  -  sigmoid
  -  sigmoid_focal_loss
  -  silu
  -  smooth_l1_loss
  -  soft_margin_loss
  -  softmax
  -  softmax_
  -  softmax_with_cross_entropy
  -  softplus
  -  softshrink
  -  softsign
  -  sparse_attention
  -  square_error_cost
  -  swish
  -  tanh
  -  tanh_
  -  tanhshrink
  -  temporal_shift
  -  thresholded_relu
  -  thresholded_relu_
  -  triplet_margin_loss
  -  triplet_margin_with_distance_loss
  -  unfold
  -  upsample
  -  zeropad2d

paddle:
  -  abs
  -  abs_
  -  acos
  -  acos_
  -  acosh
  -  acosh_
  -  add
  -  add_n
  -  addmm
  -  addmm_
  -  all
  -  allclose
  -  amax
  -  amin
  -  angle
  -  any
  -  arange
  -  argmax
  -  argmin
  -  argsort
  -  as_complex
  -  as_real
  -  as_strided
  -  asin
  -  asin_
  -  asinh
  -  asinh_
  -  assign
  -  atan
  -  atan2
  -  atan_
  -  atanh
  -  atanh_
  -  atleast_1d
  -  atleast_2d
  -  atleast_3d
  -  bernoulli
  -  bincount
  -  binomial
  -  bitwise_and
  -  bitwise_and_
  -  bitwise_not
  -  bitwise_not_
  -  bitwise_or
  -  bitwise_or_
  -  bitwise_xor
  -  bitwise_xor_
  -  bmm
  -  broadcast_shape
  -  broadcast_tensors
  -  broadcast_to
  -  cauchy_
  -  cdist
  -  ceil
  -  cholesky
  -  chunk
  -  clip
  -  column_stack
  -  combinations
  -  concat
  -  conj
  -  corrcoef
  -  copysign
  -  copysign_
  -  cos
  -  cos_
  -  cosh
  -  cosh_
  -  count_nonzero
  -  crop
  -  cross
  -  cummax
  -  cummin
  -  cumprod
  -  cumprod_
  -  cumsum
  -  cumsum_
  -  cumulative_trapezoid
  -  decomposition
  -  deg2rad
  -  diag
  -  diag_embed
  -  diagflat
  -  diagonal
  -  diagonal_scatter
  -  diff
  -  digamma
  -  digamma_
  -  divide
  -  divide_
  -  dot
  -  dsplit
  -  dstack
  -  eigvalsh
  -  einsum
  -  empty
  -  empty_like
  -  equal
  -  equal_all
  -  erf
  -  erf_
  -  erfinv
  -  exp
  -  expand
  -  expand_as
  -  expm1
  -  expm1_
  -  eye
  -  fft
  -  flatten
  -  flatten_
  -  flip
  -  floor
  -  floor_divide
  -  floor_divide_
  -  floor_mod
  -  floor_mod_
  -  fmax
  -  fmin
  -  frac
  -  frac_
  -  frexp
  -  full
  -  full_like
  -  gather
  -  gather_nd
  -  gcd
  -  gcd_
  -  greater_equal
  -  greater_equal_
  -  greater_than
  -  greater_than_
  -  heaviside
  -  histogram
  -  histogramadd
  -  hsplit
  -  hstack
  -  hypot
  -  hypot_
  -  i0
  -  i0_
  -  i0e
  -  i1
  -  i1e
  -  imag
  -  increment
  -  index_add
  -  index_add_
  -  index_fill
  -  index_fill_
  -  index_put
  -  index_put_
  -  index_sample
  -  index_select
  -  inner
  -  kron
  -  kthvalue
  -  lcm
  -  lcm_
  -  ldexp
  -  ldexp_
  -  lerp
  -  less_equal
  -  less_equal_
  -  less_than
  -  less_than_
  -  lgamma
  -  lgamma_
  -  linalg
  -  linspace
  -  log
  -  log10
  -  log10_
  -  log1p
  -  log1p_
  -  log2
  -  log2_
  -  log_
  -  logaddexp
  -  logcumsumexp
  -  logical_and
  -  logical_and_
  -  logical_not
  -  logical_not_
  -  logical_or
  -  logical_or_
  -  logical_xor
  -  logical_xor_
  -  logit
  -  logit_
  -  logspace
  -  logsumexp
  -  masked_fill
  -  masked_fill_
  -  masked_scatter
  -  masked_scatter_
  -  masked_select
  -  matmul
  -  max
  -  maximum
  -  mean
  -  median
  -  meshgrid
  -  min
  -  minimum
  -  mm
  -  mod
  -  mod_
  -  mode
  -  moveaxis
  -  multigammaln
  -  multigammaln_
  -  multinomial
  -  multiplex
  -  multiply
  -  multiply_
  -  mv
  -  nan_to_num
  -  nan_to_num_
  -  nanmean
  -  nanmedian
  -  nanquantile
  -  nansum
  -  neg
  -  neg_
  -  nextafter
  -  nonzero
  -  normal
  -  normal_
  -  not_equal
  -  not_equal_
  -  numel
  -  ones
  -  ones_like
  -  outer
  -  pdist
  -  poisson
  -  polar
  -  polygamma
  -  polygamma_
  -  pow
  -  pow_
  -  prod
  -  put_along_axis
  -  quantile
  -  rad2deg
  -  rand
  -  randint
  -  randint_like
  -  randn
  -  randperm
  -  reader
  -  real
  -  reciprocal
  -  regularizer
  -  remainder
  -  remainder_
  -  renorm
  -  renorm_
  -  repeat_interleave
  -  reshape
  -  reshape_
  -  roll
  -  rot90
  -  round
  -  row_stack
  -  rsqrt
  -  scale
  -  scatter
  -  scatter_
  -  scatter_nd
  -  scatter_nd_add
  -  searchsorted
  -  select_scatter
  -  sgn
  -  shard_index
  -  sign
  -  signal
  -  signbit
  -  sin
  -  sin_
  -  sinh
  -  sinh_
  -  slice
  -  slice_scatter
  -  sort
  -  split
  -  sqrt
  -  square
  -  square_
  -  squeeze
  -  squeeze_
  -  stack
  -  standard_gamma
  -  standard_normal
  -  stanh
  -  strided_slice
  -  subtract
  -  sum
  -  t
  -  t_
  -  take
  -  take_along_axis
  -  tan
  -  tan_
  -  tanh
  -  tanh_
  -  tensordot
  -  tile
  -  topk
  -  trace
  -  transpose
  -  transpose_
  -  trapezoid
  -  tril
  -  tril_
  -  tril_indices
  -  triu
  -  triu_
  -  triu_indices
  -  trunc
  -  trunc_
  -  unbind
  -  unflatten
  -  unfold
  -  uniform
  -  unique
  -  unique_consecutive
  -  unsqueeze
  -  unsqueeze_
  -  unstack
  -  vander
  -  var
  -  view
  -  view_as
  -  vsplit
  -  where
  -  where_
  -  zeros
  -  zeros_like

tensor:
  -  T
  -  __add__
  -  __and__
  -  __radd__
  -  __div__
  -  __eq__
  -  __floordiv__
  -  __ge__
  -  __gt__
  -  __le__
  -  __lt__
  -  __matmul__
  -  __mod__
  -  __mul__
  -  __ne__
  -  __neg__
  -  __nonezero__
  -  __or__
  -  __pow__
  -  __radd__
  -  __rdiv__
  -  __rmul__
  -  __rpow__
  -  __rsub__
  -  __rtruediv__
  -  __sub__
  -  __truediv__
  -  __xor__
  -  abs
  -  abs_
  -  acos
  -  acos_
  -  acosh
  -  acosh_
  -  add
  -  add_
  -  add_n
  -  addmm
  -  addmm_
  -  all
  -  allclose
  -  amax
  -  amin
  -  angle
  -  any
  -  argmax
  -  argmin
  -  argsort
  -  as_complex
  -  as_real
  -  as_strided
  -  asin
  -  asin_
  -  asinh
  -  asinh_
  -  atan
  -  atan2
  -  atan_
  -  atanh
  -  atanh_
  -  atleast_1d
  -  atleast_2d
  -  atleast_3d
  -  bincount
  -  bitwise_and
  -  bitwise_and_
  -  bitwise_not
  -  bitwise_not_
  -  bitwise_or
  -  bitwise_or_
  -  bitwise_xor
  -  bitwise_xor_
  -  bmm
  -  broadcast_shape
  -  broadcast_tensors
  -  broadcast_to
  -  cauchy_
  -  cdist
  -  ceil
  -  ceil_
  -  cholesky
  -  cholesky_solve
  -  clip
  -  clip_
  -  coalesce
  -  cols
  -  combinations
  -  concat
  -  cond
  -  conj
  -  contiguous
  -  corrcoef
  -  cos
  -  cos_
  -  cosh
  -  cosh_
  -  count_nonzero
  -  cov
  -  cross
  -  crows
  -  cummax
  -  cummin
  -  cumprod
  -  cumprod_
  -  cumsum
  -  cumsum_
  -  cumulative_trapezoid
  -  deg2rad
  -  diag
  -  diag_embed
  -  diagflat
  -  diagonal
  -  diagonal_scatter
  -  diff
  -  digamma
  -  digamma_
  -  divide
  -  divide_
  -  dot
  -  eig
  -  eigvals
  -  eigvalsh
  -  equal
  -  equal_all
  -  erf
  -  erfinv
  -  erfinv_
  -  exp
  -  exp_
  -  expand
  -  expand_as
  -  expm1
  -  exponential_
  -  fill_
  -  fill_diagonal_
  -  fill_diagonal_tensor
  -  fill_diagonal_tensor_
  -  flatten
  -  flatten_
  -  flip
  -  floor
  -  floor_
  -  floor_divide
  -  floor_divide_
  -  floor_mod
  -  floor_mod_
  -  fmax
  -  fmin
  -  frac
  -  frac_
  -  frexp
  -  gather
  -  gather_nd
  -  gcd
  -  gcd_
  -  get_selected_rows
  -  get_strides
  -  greater_equal
  -  greater_equal_
  -  greater_than
  -  greater_than_
  -  heaviside
  -  histogram
  -  histogramadd
  -  hsplit
  -  hstack
  -  hypot
  -  hypot_
  -  i0
  -  i0_
  -  i0e
  -  i1
  -  i1e
  -  imag
  -  increment
  -  index_add
  -  index_add_
  -  index_fill
  -  index_fill_
  -  index_put
  -  index_put_
  -  index_sample
  -  index_select
  -  inner
  -  kron
  -  kthvalue
  -  layout
  -  lcm
  -  lcm_
  -  ldexp
  -  ldexp_
  -  lerp
  -  lerp_
  -  less_equal
  -  less_equal_
  -  less_than
  -  less_than_
  -  lgamma
  -  lgamma_
  -  log
  -  log10
  -  log10_
  -  log1p
  -  log1p_
  -  log2
  -  log2_
  -  log_
  -  logaddexp
  -  logcumsumexp
  -  logical_and
  -  logical_and_
  -  logical_not
  -  logical_not_
  -  logical_or
  -  logical_or_
  -  logical_xor
  -  logical_xor_
  -  logit
  -  logit_
  -  logsumexp
  -  lstsq
  -  lu
  -  lu_unpack
  -  masked_fill
  -  masked_fill_
  -  masked_select
  -  masked_scatter
  -  masked_scatter_
  -  matmul
  -  matrix_power
  -  max
  -  maximum
  -  mean
  -  median
  -  min
  -  minimum
  -  mm
  -  mod
  -  mod_
  -  mode
  -  moveaxis
  -  multi_dot
  -  multigammaln
  -  multigammaln_
  -  multinomial
  -  multiplex
  -  multiply
  -  multiply_
  -  mv
  -  nan_to_num
  -  nan_to_num_
  -  nanmean
  -  nanmedian
  -  nanquantile
  -  nansum
  -  ndimension
  -  neg
  -  neg_
  -  nnz
  -  nonzero
  -  norm
  -  normal_
  -  not_equal
  -  not_equal_
  -  numel
  -  offset
  -  outer
  -  pca_lowrank
  -  pinv
  -  polar
  -  polygamma
  -  polygamma_
  -  pow
  -  pow_
  -  process_mesh
  -  prod
  -  put_along_axis
  -  put_along_axis_
  -  qr
  -  quantile
  -  rad2deg
  -  remainder
  -  remainder_
  -  renorm
  -  renorm_
  -  repeat_interleave
  -  reverse
  -  roll
  -  rot90
  -  round
  -  round_
  -  rows
  -  rsqrt
  -  rsqrt_
  -  scale
  -  scale_
  -  scatter
  -  scatter_
  -  scatter_nd
  -  scatter_nd_add
  -  select_scatter
  -  sgn
  -  shard_index
  -  sigmoid
  -  sigmoid_
  -  sign
  -  signbit
  -  sin
  -  sin_
  -  sinh
  -  sinh_
  -  size
  -  slice
  -  solve
  -  sort
  -  split
  -  sqrt
  -  sqrt_
  -  square
  -  squeeze
  -  squeeze_
  -  stack
  -  stanh
  -  std
  -  stft
  -  strided_slice
  -  strides
  -  subtract
  -  subtract_
  -  sum
  -  t
  -  t_
  -  take
  -  take_along_axis
  -  tan
  -  tan_
  -  tanh
  -  tanh_
  -  tensordot
  -  tile
  -  top_p_sampling
  -  topk
  -  trace
  -  transpose
  -  transpose_
  -  trapezoid
  -  tril
  -  tril_
  -  triu
  -  triu_
  -  trunc
  -  trunc_
  -  unbind
  -  unflatten
  -  unfold
  -  uniform_
  -  unique
  -  unique_consecutive
  -  unsqueeze
  -  unsqueeze_
  -  unstack
  -  vander
  -  var
  -  view
  -  view_as
  -  vsplit
  -  where
  -  where_
  -  zero_
