# path should be real path, relative path is not safe.

# Target APIs.
op_target_path: "./PaddleAPEX/Acc/configs/op_target.yaml"
custom_op_path: "./PaddleAPEX/Acc/configs/custom_op.yaml"

custom_op: False

dump_root_path: "./dump_info"

# Target Custom Fusion Ops:
cutom_op_file_path: "/root/paddlejob/workspace/xjm/PaddleNLP/paddlenlp/transformers/llama/fusion_ops.py"

# Remote Path
remote_path: "/root/paddlejob/workspace/PaddleAPEX_dump/"
Async_dump: False


# API to be omitted.
white_list: None
# white_list: "./Acc/configs/white_list.yaml"

# mode must be chosen from ["real_data", "random"]
dump_mode: "random"


# target_step is a list, dump api function will turn on at the specific step
target_step: [10]
