# path should be real path, relative path is not safe.

# Target APIs.
op_target_path: "./PaddleAPEX/Acc/configs/op_target.yaml"
dump_root_path: "./dump_info"

# API to be omitted.
white_list: None
# white_list: "./Acc/configs/white_list.yaml"

# mode must be chosen from ["real_data", "random"]
dump_mode: "real_data"


# target_step is a list, dump api function will turn on at the specific step
target_step: [0]
